# Generated by Django 4.0.4 on 2022-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ManyToManyField(blank=True, to='sms.book'),
        ),
    ]
