# Generated by Django 4.0.4 on 2022-05-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_alter_student_book_alter_student_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
