# Generated by Django 4.0.4 on 2022-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms_app', '0003_delete_book_delete_school_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=80)),
                ('publish_date', models.DateField(blank=True)),
                ('number_of_pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('principal', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('school', models.CharField(blank=True, max_length=150)),
                ('book', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
