# Generated by Django 4.0.4 on 2022-05-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_school_region_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
