# Generated by Django 4.0.4 on 2022-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('school', models.CharField(blank=True, max_length=150)),
                ('book', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
