# Generated by Django 4.0.4 on 2022-05-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0007_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='book_foreign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.book'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_foreign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.school'),
        ),
    ]
