# Generated by Django 4.0.4 on 2022-05-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0008_student_book_foreign_student_school_foreign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='book',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
