# Generated by Django 4.0.4 on 2022-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0009_remove_student_book_remove_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='book_foreign',
        ),
        migrations.AddField(
            model_name='student',
            name='book_foreign',
            field=models.ManyToManyField(null=True, to='sms_app.book'),
        ),
    ]
