# Generated by Django 4.0.4 on 2022-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0010_remove_student_book_foreign_student_book_foreign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='book_foreign',
            field=models.ManyToManyField(to='sms_app.book'),
        ),
    ]
