# Generated by Django 4.0.4 on 2022-05-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0011_alter_student_book_foreign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='book_foreign',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school_foreign',
            new_name='school',
        ),
    ]
