# Generated by Django 4.0.3 on 2022-05-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0016_alter_student_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='book',
            new_name='books',
        ),
    ]
