# Generated by Django 4.0.3 on 2022-05-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0018_remove_student_books_student_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='book',
            new_name='books',
        ),
    ]
