# Generated by Django 4.0.3 on 2022-05-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0020_alter_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='books',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
