# Generated by Django 4.0.4 on 2022-05-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0025_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
