# Generated by Django 4.0.4 on 2022-05-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0029_student_books_student_email_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='books',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
